language: swift
matrix:
  include:
    - os: osx
      osx_image: xcode8.3
install:
  - swift --version
script:
  - pod lib lint --allow-warnings --sources='https://github.com/mitsuse/pods-la.git' --verbose
  - swift build
