#!/bin/bash

if [ $(uname) = 'Darwin' ]; then
    swift --version
    swift build --verbose
else
    docker build -t swift .

    # Workaround: Use root instead of developer.
    # - docker run -u developer -v $TRAVIS_BUILD_DIR:/mnt/project swift swift test --verbose --package-path /mnt/project
    docker run -v $TRAVIS_BUILD_DIR:/mnt/project swift swift build --verbose --package-path /mnt/project
fi
